# Generated by Django 5.0 on 2024-01-11 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
