# Generated by Django 5.0 on 2024-05-15 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareab', '0002_book_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/book_cover/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='add_book',
            field=models.ManyToManyField(blank=True, related_name='added_by_user', to='shareab.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_media_link',
            field=models.URLField(default='https://www.whatsapp.com/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
