# Generated by Django 5.0 on 2024-06-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareab', '0003_alter_book_options_book_edition_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_media_link',
            field=models.CharField(max_length=255),
        ),
    ]
