# Generated by Django 5.0 on 2024-06-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareab', '0005_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus',
            field=models.CharField(choices=[('Rockville', 'ROCKVILLE CAMPUS'), ('Takoma', 'TAKOMA PARK/SILVER SPRING CAMPUS'), ('Germantown', 'GERMANTOWN CAMPUS')], max_length=10),
        ),
    ]
