# Generated by Django 5.0 on 2024-06-19 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareab', '0006_alter_profile_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
